production:
  adapter: postgresql
  encoding: unicode
  database: Assignment_prod
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: Assignment_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: Assignment_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432