# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be1d734df96b54ed61cf21de15d2ea648a942e7b400a0b3346830060496de7a64fc3780994189f6d51363e0b390b699535f4bb801ebf91f9d73edde132ec4119

test:
  secret_key_base: ff9e298615e583a126f4ea0c1d2edabdc51f3efd1fbc4f9d6515579287afba190afa493c97ad33534a15d65f2e3c02174a74458a628bdca0b954b9f6c895a602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
